sudo: false
dist: trusty

language: php

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - composer
    - $HOME/.npm
    - $HOME/.composer/cache

install:
  - curl -s http://getcomposer.org/installer | php

php:
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  #- WP_VERSION=4.7 WP_MULTISITE=0

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=5.7.*"
  - composer require satooshi/php-coveralls '~1.0'

script:
  - composer install --no-interaction --no-progress
  - phpunit --configuration phpunit.xml.dist --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls --verbose --exclude-no-stmt
