sudo: false
dist: trusty

language: php

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - composer
    - $HOME/.npm
    - $HOME/.composer/cache

install:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - curl -s http://getcomposer.org/installer | php
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0

before_script:
  - composer require satooshi/php-coveralls '~1.0'
  - composer install --no-interaction --no-progress --dev

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls --verbose --exclude-no-stmt
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
